[package]
name = "garble"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"], optional = true }

[dev-dependencies]
quickcheck = "1"
quickcheck_macros = "1"
