[package]
name = "garble_lang"
version = "0.1.1"
edition = "2021"
rust-version = "1.60.0"
description = "Turing-Incomplete Programming Language for Multi-Party Computation with Garbled Circuits"
repository = "https://github.com/sine-fdn/garble/"
license = "MIT"
categories = ["command-line-utilities", "compilers"]
keywords = ["programming-language", "secure-computation", "garbled-circuits", "circuit-description", "smpc"]

[dependencies]
serde = { version = "1.0", features = ["derive"], optional = true }

[dev-dependencies]
quickcheck = "1"
quickcheck_macros = "1"
